### ISSUE TITLE
fix imports to multiformats/go-multiaddr

### ISSUE THREAD

**Issue by jbenet** [multiformats/go-multiaddr-net#21]

**Comment by keks** [comment]
Yeah i just ran into this. I guess a lot of code will break if the import is simply changed to import `multiformats/go-multiaddr`, right?

**Comment by whyrusleeping** [comment]
@keks Nothing would break immediately, since deps are frozen with gx nothing will change until we go to update the package. Once we decide to update the package we will have to make a lot of changes up the stack.

**Comment by keks** [comment]
Oh, I didn't think about gx. But yeah, changes to the stack are obvious.

**Comment by hsanjuan** [comment]
this seems fixed
