### ISSUE TITLE
Helper functions to detect private IP addresses

### ISSUE THREAD

**Issue by JustinDrake** [multiformats/go-multiaddr-net#28]
We have `IsIPLoopback`, `IsIP6LinkLocal` and `IsIPUnspecified`, but missing functions to filter the following kinds of private addresses:

- `/ip4/10.0.0.2/tcp/9005/ws`
- `/ip4/172.18.0.7/tcp/4001`
- `/ip4/192.168.1.158/tcp/4001`

The range 10.0.0.0 - 10.255.255.255 is called "class A private IPs".
The range 172.16.0.0 - 172.31.255.255 is called "class B private IPs".
The range 192.168.0.0 - 192.168.255.255 is called "class C private IPs".

**Comment by lgierth** [comment]
This is largely covered by #46
