### ISSUE TITLE
Bug/inconsistency with IsIPLoopback

### ISSUE THREAD

**Issue by JustinDrake** [multiformats/go-multiaddr-net#29]
The following prints `true`, `true`, `true`, `false`. IPv4 and IPv6 addresses are not handled consistently.

	multiaddr = ma.StringCast("/ip4/127.0.0.1")
	fmt.Println(manet.IsIPLoopback(multiaddr))
	multiaddr = ma.StringCast("/ip4/127.0.0.1/tcp/4001")
	fmt.Println(manet.IsIPLoopback(multiaddr))

	multiaddr = ma.StringCast("/ip6/::1")
	fmt.Println(manet.IsIPLoopback(multiaddr))
	multiaddr = ma.StringCast("/ip6/::1/tcp/4001")
	fmt.Println(manet.IsIPLoopback(multiaddr))

**Comment by Kubuxu** [comment]
Should be resolved by #27
