### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by jimpo** [multiformats/go-multiaddr-net#30]
What is the best interface for TLS-enabled variants of `manet.Dial` and `manet.Listen`? In the Go stdlib, the `crypto/tls` package implements functions:

```
func Dial(network, addr string, config *Config) (*Conn, error)
func Listen(network, laddr string, config *Config) (net.Listener, error)
```

The `net/http` package sets the precedent of appending "TLS" to the end of TLS-enabled function names with `http.ListenAndServeTLS`.

How do you feel about adding to go-multiaddr-net the following functions?

```
func DialTLS(remote ma.Multiaddr, config *tls.Config) (*Conn, error)
func ListenTLS(laddr ma.Multiaddr, config *tls.Config) (Listener, error)
```

Another option would be to include the TLS information in the multiaddr struct, which I posted about here: https://github.com/multiformats/multiaddr/issues/47.

**Comment by Stebalien** [comment]
I'd rather not make this package depend on TLS, go is really bad about trimming deps it doesn't need. Maybe this deserves a new go-multiaddr-tls package (if someone really needs it)?
