### ISSUE TITLE
IsIPLoopback: fe80::1 is not a loopback address according to any standard

### ISSUE THREAD

**Issue by mwnx** [multiformats/go-multiaddr-net#39]
Hi,

While reading the code, I noticed the following:

```
	// IP6LinkLocalLoopback is the ip6 link-local loopback multiaddr
	IP6LinkLocalLoopback = ma.StringCast("/ip6/fe80::1")
[...]
// Loopback multiaddr prefixes. Any multiaddr beginning with one of the
// following byte sequences is considered a loopback multiaddr.
var loopbackPrefixes = [][]byte{
	{ma.P_IP4, 127}, // 127.*
	IP6LinkLocalLoopback.Bytes(),
	IP6Loopback.Bytes(),
}
[...]
// IsIPLoopback returns whether a Multiaddr is a "Loopback" IP address
// This means either /ip4/127.*.*.*, /ip6/::1, or /ip6/fe80::1
func IsIPLoopback(m ma.Multiaddr) bool {
	b := m.Bytes()
	for _, prefix := range loopbackPrefixes {
		if bytes.HasPrefix(b, prefix) {
			return true
		}
	}
	return false
}
```

However, as far as I can tell, there is no standard specifying that fe80::1 should be reserved as some kind of loopback and it only seems to act as such on MacOS's loopback interface (lo0). It might then be tempting to declare that only `fe80::1%lo0` is a loopback address but even that would be incorrect since it is perfectly valid (e.g. on a linux system) to create an interface named "lo0" where `fe80::1` would not be a loopback address. To make matters worse it would seem that docker sets up `fe80::1%docker0` as an IP address for its default bridge gateway by default.

I can see that this behaviour has been around since 2014, but all in all, I do not see it as reasonable. If there is a standard that reserves the use of `fe80::1` as a loopback address that I have missed, I'd be glad to see it though.

By the way, I am working on adding a way of specifying a zone ID (e.g. `%eth0`) to multiaddr ipv6 addresses (which will require a new protocol code though).

**Comment by Stebalien** [comment]
Yeah, you're right. That's not a loopback address.

Also, we should probably add `::ffff:127.*.*.*` to that list as that *is* a valid loopback address (effectively).

**Comment by Stebalien** [comment]
So, without support for zones, *none* of the link-local addresses are really "loopback". However, if you get link-local address support working, this function will need to check if the interface is a loopback interface using `net.InterfaceByIndex`.

**Comment by Stebalien** [comment]
(fixed)
