### ISSUE TITLE
multiaddr-net should not vendor multiaddr

### ISSUE THREAD

**Issue by whyrusleeping** [multiformats/go-multiaddr-net#4]
having multiaddr-net vendoring multiaddr makes using it elsewhere really difficult. I'm using multiaddr and multiaddr net in iptb and i get this:

```
# github.com/whyrusleeping/iptb
./main.go:277: cannot use maddr (type "github.com/jbenet/go-multiaddr".Multiaddr) as type "github.com/jbenet/go-multiaddr-net/Godeps/_workspace/src/github.com/jbenet/go-multiaddr".Multiaddr in argument to manet.DialArgs:
    "github.com/jbenet/go-multiaddr".Multiaddr does not implement "github.com/jbenet/go-multiaddr-net/Godeps/_workspace/src/github.com/jbenet/go-multiaddr".Multiaddr (wrong type for Decapsulate method)
        have Decapsulate("github.com/jbenet/go-multiaddr".Multiaddr) "github.com/jbenet/go-multiaddr".Multiaddr
        want Decapsulate("github.com/jbenet/go-multiaddr-net/Godeps/_workspace/src/github.com/jbenet/go-multiaddr".Multiaddr) "github.com/jbenet/go-multiaddr-net/Godeps/_workspace/src/github.com/jbenet/go-multiaddr".Multiaddr
```

**Comment by jbenet** [comment]
Godeps should fix it all for us-- it should pull everything to the top level. is this not happening?

@cryptix is right, may be time to bite the bullet and write the tools we need. will also force us to make ipfs better to make sure it's all good.

we can setup an interim pinner with pinbot until s3 works...

**Comment by cryptix** [comment]
> Godeps should fix it all for us-- it should pull everything to the top level. is this not happening?

You need to rewirte your new code with godep first for that to happen..

**Comment by Gaboose** [comment]
I too just encountered this problem. [Gopher Academy](http://blog.gopheracademy.com/advent-2014/deps/) makes the distinction between consuming and authoring libraries:

> Godep as the consumer of third-party packages, and [gopkg.in](http://labix.org/gopkg.in) as a library author.

To compare Godep and gopkg in a gist, if A imports B and B imports C:
* Godep on B secures B (itself) and potentially screws A.
* gopkg on B secures A, but not itself (gopkg on C would secure B)

Since I'm A, I naturally wish that you used gopkg :)

**Comment by jbenet** [comment]
Since i'm Sane, i want to burn godeps to the ground and teach the go community about [sane package imports](https://www.npmjs.com/).

maybe multiaddr-net should use https://github.com/whyrusleeping/gx

**Comment by Gaboose** [comment]
I just found out about Go 1.5 Vendor Experiment. It allows you to version dependencies without rewriting import paths. Gx doesn't take advantage of this.

It would still introduce whyrusleeping's error, but to fix it you would only have to
```
rm -r vendor/github.com/jbenet/go-multiaddr-net/vendor/jbenet/go-multiaddr
```

**Comment by whyrusleeping** [comment]
guys, use gx. its better now :D

**Comment by Gaboose** [comment]
what if `ln -s vendor/ipfs /ipfs` and `import "ipfs/<hash>" `?
:O

**Comment by whyrusleeping** [comment]
@Gaboose take a look at #12, we're getting closer and closer. We dont quite want to force people to use ipfs in order to use the code, so the symlink isnt an option (yet!)

**Comment by hsanjuan** [comment]
this has been fixed with gx
