### ISSUE TITLE
Add an alternative to DialArgs that doesn't stringify the results

### ISSUE THREAD

**Issue by Stebalien** [multiformats/go-multiaddr-net#67]
Unfortunately, `DialArgs` stringifies its results and `ToNetAddr` will return custom `net.Addr` objects for transports other than those in go's `net` package. For example, a websocket address will yield a special `net.Addr` where `Network()` returns "websocket".

We should implement some form of `SplitThinWaist` or `ToThinWaist` function that:

1. Parses the "thin waist" part of the address (ip/tcp/udp).
2. Returns a `net.Addr` for that part, along with the remainder of the multiaddr.

**Comment by Stebalien** [comment]
We should re-implement `DialArgs` in terms of this function (should be trivial).

**Comment by willscott** [comment]
Note: this will introduce a functional difference: in the case of `/dns/<hostname>` addresses, a `net.Addr` representation will perform DNS resolution, whereas the `dialargs` representation leaves the hostname as an unprocessed string.

**Comment by Stebalien** [comment]
Ah, hm. That's unfortunate. And probably why we didn't do this.

**Comment by willscott** [comment]
Lets close this until we have a specific use case needing something more than what is currently exposed, so we can make sure we're getting the right interface.
